ingress:
  hostname: keycloak-hostname

resources:
  limits:
    cpu: 1400m
    memory: 3Gi
  requests:
    cpu: 1000m
    memory: 2.5Gi

## @param nodeSelector Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##

nodeSelector:
  beta.kubernetes.io/instance-type: Standard_B2s


