apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: immudb
  labels: 
    app.kubernetes.io/component: immudb
    app: immudb
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  serviceName: immudb
  replicas: {{ .Values.immudb.replicaCount }}
  {{- if .Values.immudb.updateStrategy }}
  strategy: {{- toYaml .Values.immudb.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: 
      app: immudb
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app: immudb
        app.kubernetes.io/component: immudb
        {{- if .Values.immudb.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.immudb.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.immudb.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.immudb.nodeSelector "context" $) | nindent 8 }}
      {{- end }}      
      {{- if .Values.immudb.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.immudb.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.immudb.priorityClassName }}
      priorityClassName: {{ .Values.immudb.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.immudb.schedulerName }}
      schedulerName: {{ .Values.immudb.schedulerName | quote }}
      {{- end }}
      {{- if .Values.immudb.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.immudb.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.volumePermissions.enabled }}
        - name: volume-permissions
          image: {{ include "immudb.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command: {}
          
          securityContext: {{- include "common.tplvalues.render" (dict "value" .Values.volumePermissions.containerSecurityContext "context" $) | nindent 12 }}
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: foo
              mountPath: bar
        {{- end }}
        {{- if .Values.immudb.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.immudb.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: immudb
          image: {{ template "immudb.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.immudb.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.immudb.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.immudb.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.immudb.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.immudb.args }}
          args: [{{- range $index, $str := .Values.immudb.args }}{{ if eq $index 0 }}{{- . | quote }} {{ else }},{{  . | quote }} {{- end }}{{- end }}]
          {{- end }}
          
          
          {{- if .Values.immudb.resources }}
          resources: {{- toYaml .Values.immudb.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.immudb.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.immudb.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.immudb.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.immudb.sidecars "context" $) | nindent 8 }}
        {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
              protocol: TCP
            - name: hazelcast
              containerPort: {{ .Values.containerPorts.hazelcast }}
              protocol: TCP
            - name: prometheus
              containerPort: {{ .Values.containerPorts.prometheus }}
              protocol: TCP
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.immudb.livenessProbe.enabled }}
          livenessProbe:
             httpGet:
               path: {{ .Values.immudb.livenessProbe.path }}
               port: 9000
             initialDelaySeconds: {{ .Values.immudb.livenessProbe.initialDelaySeconds }}
             periodSeconds: {{ .Values.immudb.livenessProbe.periodSeconds }}
             timeoutSeconds: {{ .Values.immudb.livenessProbe.timeoutSeconds }}
          
          {{- else if .Values.immudb.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.immudb.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.immudb.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.immudb.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.immudb.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.immudb.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.immudb.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.immudb.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.immudb.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.immudb.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.immudb.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.immudb.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.immudb.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.immudb.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.immudb.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.immudb.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.immudb.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.immudb.extraEnvVarsSecret "context" $) }}
            {{- end }}
            
      {{- if .Values.serviceAccount.create }}    
      serviceAccountName: {{ template "immudb.serviceAccountName" . }}
      {{- end }}
      {{- include "immudb.imagePullSecrets" . | nindent 6 }}
      
      {{- if .Values.immudb.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.immudb.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.immudb.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.immudb.affinity "context" $) | nindent 8 }}
      {{/*- if .Values.immudb.podAffinityPreset or .Values.immudb.podAntiAffinityPreset or  .Values.immudb.nodeAffinityPreset.type */}}
      {{- else }}
      affinity:
        {{- if .Values.immudb.podAffinityPreset}}
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.immudb.podAffinityPreset "component" "immudb" "context" $) | nindent 10 }}
        {{- end}}
        {{- if .Values.immudb.podAntiAffinityPreset }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.immudb.podAntiAffinityPreset "component" "immudb" "context" $) | nindent 10 }}
        {{- end}}
        {{- if .Values.immudb.nodeAffinityPreset.type }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.immudb.nodeAffinityPreset.type "key" .Values.immudb.nodeAffinityPreset.key "values" .Values.immudb.nodeAffinityPreset.values) | nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
        {{- if .Values.immudb.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.immudb.extraVolumes "context" $) | nindent 8 }}
        {{- end }}

  volumeClaimTemplates:
    - metadata:
        name: "data"
        {{- if .Values.immudb.persistence.annotations }}
        annotations: {{- toYaml .Values.immudb.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes: {{- toYaml .Values.immudb.persistence.accessModes | nindent 10 }}
        {{- if .Values.immudb.persistence.storageClass }}        
        {{ $storage := dict "global" .Values.global "local" .Values.immudb }}
        {{- include "immudb.storageClass" $storage }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.immudb.persistence.size | quote }}
        {{- if .Values.immudb.persistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.immudb.persistence.selector "context" $) | nindent 10 }}
        {{- else if .Values.immudb.persistence.existingVolume }}
        selector:
          matchLabels:
            volume: {{ .Values.immudb.persistence.existingVolume }}
        {{- end }}

