apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: aaa-admin
  namespace: {{ .Values.nameSpace }}
  labels: 
    app.kubernetes.io/component: admin
    app: aaa-admin
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.admin.replicaCount }}
  {{- if .Values.admin.updateStrategy }}
  strategy: {{- toYaml .Values.admin.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: 
      app: aaa-admin
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app: aaa-admin
        app.kubernetes.io/component: admin
        {{- if .Values.admin.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.admin.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.admin.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.admin.nodeSelector "context" $) | nindent 8 }}
      {{- end }}      
      {{- if .Values.admin.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.admin.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.admin.priorityClassName }}
      priorityClassName: {{ .Values.admin.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.admin.schedulerName }}
      schedulerName: {{ .Values.admin.schedulerName | quote }}
      {{- end }}
      {{- if .Values.admin.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.admin.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.volumePermissions.enabled }}
        - name: volume-permissions
          image: {{ include "catalogue.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command: {}
          
          securityContext: {{- include "common.tplvalues.render" (dict "value" .Values.volumePermissions.containerSecurityContext "context" $) | nindent 12 }}
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: foo
              mountPath: bar
        {{- end }}
        {{- if .Values.admin.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.admin.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: aaa-admin
          image: {{ template "catalogue.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.admin.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.admin.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.admin.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.admin.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.admin.args }}
          args: [{{- range $index, $str := .Values.admin.args }}{{ if eq $index 0 }}{{- . | quote }} {{ else }},{{  . | quote }} {{- end }}{{- end }}]
          {{- end }}
          
          
          {{- if .Values.admin.resources }}
          resources: {{- toYaml .Values.admin.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.admin.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.admin.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.admin.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.admin.sidecars "context" $) | nindent 8 }}
        {{- end }}
          ports:
            - name: hazelcast
              containerPort: {{ .Values.containerPorts.hazelcast }}
              protocol: TCP
            - name: prometheus
              containerPort: {{ .Values.containerPorts.prometheus }}
              protocol: TCP
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.admin.livenessProbe.enabled }}
          livenessProbe:
             httpGet:
               path: {{ .Values.admin.livenessProbe.path }}
               port: 9000
             initialDelaySeconds: {{ .Values.admin.livenessProbe.initialDelaySeconds }}
             periodSeconds: {{ .Values.admin.livenessProbe.periodSeconds }}
             timeoutSeconds: {{ .Values.admin.livenessProbe.timeoutSeconds }}
          
          {{- else if .Values.admin.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.admin.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.admin.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.admin.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.admin.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.admin.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.admin.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.admin.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.admin.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.admin.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.admin.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.admin.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            {{- if .Values.admin.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.admin.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.admin.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.admin.extraEnvVarsSecret "context" $) }}
            {{- end }}
            {{- if .Values.admin.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.admin.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
      {{- if .Values.serviceAccount.create }}    
      serviceAccountName: {{ template "catalogue.serviceAccountName" . }}
      {{- end }}
      {{- include "catalogue.imagePullSecrets" . | nindent 6 }}
      
      {{- if .Values.admin.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.admin.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.admin.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.admin.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        {{- if .Values.admin.podAffinityPreset}}
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.admin.podAffinityPreset "component" "admin" "context" $) | nindent 10 }}
        {{- end}}
        {{- if .Values.admin.podAntiAffinityPreset }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "component" "admin" "context" $) | nindent 10 }}
        {{- end}}
        {{- if .Values.admin.nodeAffinityPreset.type }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.admin.nodeAffinityPreset.type "key" .Values.admin.nodeAffinityPreset.key "values" .Values.catalogue.nodeAffinityPreset.values) | nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
        {{- if .Values.admin.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.admin.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
