controller:
  resources:
    limits:
      cpu: 100m
      memory: 0.1Gi
    requests:
      cpu: 100m
      memory: 0.1Gi

  ## @param nodeSelector Node labels for pod assignment
 ### ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector:
    node.kubernetes.io/instance-type: t3a.large
  # AWS network load-balancer provisioning in-front of ingress controller as service
  service:
    enabled: true
    annotations: 
      ## in-tree aws cloud provider loadbalancer controller is used, 
      ## specified using annotations 
      ## Ref: https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      ## AWS elastic ip is assigned to the ingress nlb 
      ## It needs to be provisioned in aws before-hand and 
      ## its epialloc-id needs to be specified
      service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "<eipalloc-id>"
      ## Explictly specifying the AZ in nlb will route traffic to 
      ## https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/#subnets
      service.beta.kubernetes.io/aws-load-balancer-subnets: "<subnet-id>"

    labels: {}
    
    # clusterIP: ""

    ## List of IP addresses at which the controller services are available
    ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
    ##
    externalIPs: []

    # loadBalancerIP: ""
    loadBalancerSourceRanges: []

    enableHttp: true
    enableHttps: true

    ## Set external traffic policy to: "Local" to preserve source IP on
    ## providers supporting it
    ## Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
    externalTrafficPolicy: "Local"
    # Must be either "None" or "ClientIP" if set. Kubernetes will default to "None".
    # Ref: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
    # sessionAffinity: ""

    # specifies the health check node port (numeric port number) for the service. If healthCheckNodePort isn’t specified,
    # the service controller allocates a port from your cluster’s NodePort range.
    # Ref: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
    # healthCheckNodePort: 0

    ports:
      http: 80
      https: 443

    targetPorts:
      http: http
      https: https

    type: LoadBalancer

    ## Enables an additional internal load balancer (besides the external one).
    ## Annotations are mandatory for the load balancer to come up. Varies with the cloud service.
    internal:
      enabled: false
      annotations: {}

      # loadBalancerIP: ""

      ## Restrict access For LoadBalancer service. Defaults to 0.0.0.0/0.
      loadBalancerSourceRanges: []

      ## Set external traffic policy to: "Local" to preserve source IP on
      ## providers supporting it
      ## Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
      # externalTrafficPolicy: ""


defaultBackend:
  resources:
    limits:
      cpu: 20m
      memory: 30Mi
    requests:
      cpu: 10m
      memory: 20Mi
  ## @param nodeSelector Node labels for pod assignment
  ### ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector:
    node.kubernetes.io/instance-type: t3.medium

