postgresql:
  resources:
    limits:
       cpu: 1500m
       memory: 3.5Gi
    requests:
       cpu: 1200m
       memory: 3Gi
  maxConnections: 300
  nodeSelector:
    node.kubernetes.io/instance-type: t3.medium

pgpool:
  resources:
    limits:
       cpu: 1400m
       memory: 1024Mi
    requests:
       cpu: 1200m
       memory: 712Mi
  ## The number of preforked Pgpool-II server processes. It is also the concurrent
  ## connections limit to Pgpool-II from clients. Must be a positive integer. (PGPOOL_NUM_INIT_CHILDREN)
  ## ref: https://github.com/bitnami/bitnami-docker-pgpool#configuration
  ##
  numInitChildren: 200

  ## The maximum number of cached connections in each child process (PGPOOL_MAX_POOL)
  ## ref: https://github.com/bitnami/bitnami-docker-pgpool#configuration
  ##
  maxPool: 2

  ## Affinity for Pgpool pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ## Note: pgpool.podAffinityPreset, pgpool.podAntiAffinityPreset, and pgpool.nodeAffinityPreset will be ignored when it's set
  ##
  affinity:
  #podAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #    - labelSelector:
  #        matchExpressions:
  #        - key: app.kubernetes.io/component
  #          operator: In
  #          values:
  #          - postgresql
  #      topologyKey: "kubernetes.io/hostname"
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/component
            operator: In
            values:
            - pgpool
        topologyKey: "kubernetes.io/hostname"


  ## Node labels for Pgpool pods assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector:
    node.kubernetes.io/instance-type: t3.medium

persistence:
  storageClass: "ebs-csi-storage-class"
  accessModes:
    - ReadWriteOnce
  size: 30Gi


