apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: lip-redis
  namespace: {{ .Values.nameSpace }}
  labels: 
    app.kubernetes.io/component: redis
    app: lip-redis
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  {{- if .Values.redis.updateStrategy }}
  strategy: {{- toYaml .Values.redis.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: 
      app: lip-redis
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app: lip-redis
        app.kubernetes.io/component: redis
        {{- if .Values.redis.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.redis.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.redis.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.redis.nodeSelector "context" $) | nindent 8 }}
      {{- end }}      
      {{- if .Values.redis.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.redis.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.redis.priorityClassName }}
      priorityClassName: {{ .Values.redis.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.redis.schedulerName }}
      schedulerName: {{ .Values.redis.schedulerName | quote }}
      {{- end }}
      {{- if .Values.redis.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.redis.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.volumePermissions.enabled }}
        - name: volume-permissions
          image: {{ include "catalogue.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command: ["sh","-c","mkdir -p /temp-dir && chown -R 1001:1001 /temp-dir"]
          securityContext: {{- include "common.tplvalues.render" (dict "value" .Values.volumePermissions.containerSecurityContext "context" $) | nindent 12 }}
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: async-dir
              mountPath: "/temp-dir"
        {{- end }}
        {{- if .Values.redis.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.redis.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: lip-redis
          image: {{ template "catalogue.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.redis.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.redis.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.redis.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.redis.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.redis.args }}
          args: [{{- range $index, $str := .Values.redis.args }}{{ if eq $index 0 }}{{- . | quote }} {{ else }},{{  . | quote }} {{- end }}{{- end }}]
          {{- end }}
          
          
          {{- if .Values.redis.resources }}
          resources: {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.redis.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.redis.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.redis.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.redis.sidecars "context" $) | nindent 8 }}
        {{- end }}
          ports:
            - name: hazelcast
              containerPort: {{ .Values.containerPorts.hazelcast }}
              protocol: TCP
            - name: prometheus
              containerPort: {{ .Values.containerPorts.prometheus }}
              protocol: TCP
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.redis.livenessProbe.enabled }}
          livenessProbe:
             httpGet:
               path: {{ .Values.redis.livenessProbe.path }}
               port: 9000
             initialDelaySeconds: {{ .Values.redis.livenessProbe.initialDelaySeconds }}
             periodSeconds: {{ .Values.redis.livenessProbe.periodSeconds }}
             timeoutSeconds: {{ .Values.redis.livenessProbe.timeoutSeconds }}
          
          {{- else if .Values.redis.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.redis.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.redis.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.redis.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.redis.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.redis.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.redis.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.redis.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- else if .Values.redis.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.redis.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.redis.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.redis.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            {{- if .Values.redis.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.redis.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.redis.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.redis.extraEnvVarsSecret "context" $) }}
            {{- end }}
            {{- if .Values.redis.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.redis.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
      {{- if .Values.serviceAccount.create }}    
      serviceAccountName: {{ template "catalogue.serviceAccountName" . }}
      {{- end }}
      {{- include "catalogue.imagePullSecrets" . | nindent 6 }}
      
      {{- if .Values.redis.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.redis.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.redis.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.redis.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        {{- if .Values.redis.podAffinityPreset}}
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.redis.podAffinityPreset "component" "redis" "context" $) | nindent 10 }}
        {{- end}}
        {{- if .Values.redis.podAntiAffinityPreset }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "component" "redis" "context" $) | nindent 10 }}
        {{- end}}
        {{- if .Values.redis.nodeAffinityPreset.type }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.redis.nodeAffinityPreset.type "key" .Values.redis.nodeAffinityPreset.key "values" .Values.catalogue.nodeAffinityPreset.values) | nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
        {{- if .Values.redis.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.redis.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
